/**
 * Config YAML generator for signet.
 * Uses template literals (NOT YAML.stringify) to preserve comments.
 */

export interface InitOptions {
  channel: string;
  browserDataDir: string;
  credentialsDir: string;
  headlessTimeout: number;
  visibleTimeout: number;
  waitUntil: string;
  providers?: Array<{
    id: string;
    domains: string[];
    strategy: string;
    entryUrl?: string;
    config?: Record<string, unknown>;
  }>;
}

function yamlArray(items: string[]): string {
  return `[${items.map(d => `"${d}"`).join(', ')}]`;
}

function renderProviderConfig(config: Record<string, unknown>, indent: number): string {
  const spaces = ' '.repeat(indent);
  const lines: string[] = [];
  for (const [key, value] of Object.entries(config)) {
    if (Array.isArray(value)) {
      lines.push(`${spaces}${key}: ${yamlArray(value as string[])}`);
    } else if (typeof value === 'string') {
      lines.push(`${spaces}${key}: ${value}`);
    } else if (typeof value === 'number' || typeof value === 'boolean') {
      lines.push(`${spaces}${key}: ${String(value)}`);
    }
  }
  return lines.join('\n');
}

function renderProvider(provider: {
  id: string;
  domains: string[];
  strategy: string;
  entryUrl?: string;
  config?: Record<string, unknown>;
}): string {
  const lines: string[] = [];
  lines.push(`  ${provider.id}:`);
  lines.push(`    domains: ${yamlArray(provider.domains)}`);
  lines.push(`    strategy: ${provider.strategy}`);
  if (provider.entryUrl) {
    lines.push(`    entryUrl: ${provider.entryUrl}`);
  }
  if (provider.config && Object.keys(provider.config).length > 0) {
    lines.push('    config:');
    lines.push(renderProviderConfig(provider.config, 6));
  }
  return lines.join('\n');
}

/**
 * Generate a commented YAML config string from the given options.
 * Uses template literals to preserve comments and formatting.
 */
export function generateConfigYaml(options: InitOptions): string {
  const providerSection = options.providers && options.providers.length > 0
    ? options.providers.map(p => renderProvider(p)).join('\n\n')
    : `  # No providers configured yet.
  # Add providers here or use "sig login <url>" for auto-provisioning.
  #
  # Example — cookie-based (SSO):
  #   my-jira:
  #     domains: ["jira.example.com"]
  #     strategy: cookie
  #     config:
  #       ttl: "12h"
  #
  # Example — API token:
  #   github:
  #     domains: ["github.com", "api.github.com"]
  #     strategy: api-token
  #     config:
  #       headerName: Authorization
  #       headerPrefix: Bearer`;

  return `# Signet unified configuration
# Generated by "sig init". All configuration lives in this single file.
# Documentation: https://github.com/pylon/signet

# Browser settings (required)
# Controls browser automation for cookie and OAuth2 authentication.
browser:
  browserDataDir: ${options.browserDataDir}   # Persistent browser profile directory
  channel: ${options.channel}                        # Browser channel (chrome, msedge, chromium)
  headlessTimeout: ${options.headlessTimeout}                 # Timeout for headless auth attempt (ms)
  visibleTimeout: ${options.visibleTimeout}                # Timeout for visible/user-assisted auth (ms)
  waitUntil: ${options.waitUntil}                       # Page load condition (load, networkidle, domcontentloaded, commit)

# Storage settings (required)
# Where per-provider credential files are stored.
storage:
  credentialsDir: ${options.credentialsDir}   # Per-provider credential files directory

# Remote credential stores (optional)
# Sync credentials to/from remote machines via SSH.
# remotes:
#   dev-server:
#     type: ssh
#     host: dev.example.com
#     user: deploy
#     path: ~/.signet/credentials
#     sshKey: ~/.ssh/id_ed25519

# Provider configurations
# Cookie-based providers (most SSO systems) don't need config at all —
# just call "sig login https://jira.example.com" and it auto-provisions.
# Only create entries here for OAuth2, API tokens, or advanced settings.
providers:
${providerSection}
`;
}
